#!/bin/bash
# Check number of arguments
if [ "$#" -lt 3 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME [PATH_TO_SSH_KEY]"
    exit 1
fi

# Assign arguments to variables
FILE="$1"
IP="$2"
USERNAME="$3"
SSH_KEY="$4"

# If SSH key path is not provided, use the default
if [ -z "$SSH_KEY" ]; then
    SSH_KEY="$HOME/.ssh/id_rsa"
fi

#disable strict host key check
scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE" "$USERNAME@$IP":~

